#define THERMISTOR_PIN A1
#define SERIESRESISTOR 100000
#define THERMISTORNOMINAL 100000
#define TEMPERATURENOMINAL 25
#define BCOEFFICIENT 3950
#define NUMSAMPLES 10
#define RELAY_PIN 3
#define GLOBAL_TEXT_SIZE 1.7
#define POSXDEF 5

#define BTN_UP 2
#define BTN_DOWN 4